### ISSUE TITLE
Implement HMAC-SHA1 signature method

### ISSUE THREAD

**Issue by nbeyer** [cerner/cerner-oauth1a#1]
### Description of Issue
v1.0.0 hard codes the use of PLAINTEXT signatures. This is acceptable given the use of a service provider that is only interacted with via HTTPS, which is what all Cerner-managed providers are. For any other provider that may also implement this variant B2B workflow, it would be helpful to provide HMAC-SHA1 signatures to protect use over HTTP.

#### Project Version
v1.0.0

### Expected Outcomes
- cerner-oauth1a can interact with a provider using HMAC-SHA1 signatures

**Comment by johnlcox** [comment]
HMAC-SHA1 provider validation support is needed for APIs that are being called from Millennium.

**Comment by nab0310** [comment]
Implementing this, in my head poses an interesting design question. According to [rfc5849](https://tools.ietf.org/html/rfc5849#section-3.4.2), the HMAC-SHA1 signatures are signed by using a `base signature string` that is computed from tying different parts of the HTTP request that the token is attached to together (https://tools.ietf.org/html/rfc5849#section-3.4.1.1). 

Currently, within cerner-oauth1a the `AccessToken` is primarily constructed by using just the `Authorization` header (via the `from_authorization_header` method), which contains no request information attached to it. In order to perform either the Service Provider or Consumer use cases, I believe we would need to have the request information in order to correctly validate the`oauth_signature` on the requests that are signed using HMAC-SHA1. This is a fairly large departure from how the library currently works, and I wanted to get some feedback on my preliminary design.

I would like to propose the following design:
1. Something similar to the design pattern for request_proxy in https://github.com/oauth-xx/oauth-ruby is used to help convert multiple types of requests to an single `Cerner::OAuth1a::Request` (name still pending) object. (see https://github.com/nab0310/cerner-oauth1a/blob/hmac-sha1/lib/cerner/oauth1a/request_proxy/rack_request.rb and https://github.com/nab0310/cerner-oauth1a/blob/hmac-sha1/lib/cerner/oauth1a/request_proxy/base.rb) 
My branch uses a `proxies` DSL method to register classes that are used for deserialization of Request objects, but if you have any better ideas, I'm all for it. 

2. Those conversion classes are conditionally loaded, in order to reduce dependencies. (see https://github.com/nab0310/cerner-oauth1a/blob/659e42c90101ac84948601f8e3f741dfa5a3eaff/lib/cerner/oauth1a.rb#L11)

3. A new parameter is added to the `AccessToken` class that stores the `signature_base_string` for the request.
>A sidenote on `signature_base_string`; because it is defined primarily by myself and an rfc definition, I'm having trouble with managing that abstraction. I'm not sure if it should be included as a parameter on the `AccessToken` class or if the `Cerner::OAuth1a::Request` object should be included.

4. A method `from_request` is added to `AccessToken` that takes in a foregin request object, converts it (if it can) to a `Cerner::OAuth1a::Request` object, and constructs an `AccessToken`. An error would be thrown if the request passed in is not one of the supported request types.

5. The `signature_base_string` on the `AccessToken` object is used, along with the `Consumer Secret` and `Token Secret` to verify the request signature if it is signed with HMAC.

6. When it comes to generating HMAC tokens, we would need to verify that the `signature_base_string` is present on the AccessToken but then we have everything we need to make it.

I made a branch with some preliminary changes, adding in the design for the request_proxy as well as the support for handling `Rack::Request` objects being passed into the `from_request` method (its not ready for a PR yet, there is formatting issues and some other changes I want to make but its enough to start a conversation)

https://github.com/nab0310/cerner-oauth1a/tree/hmac-sha1

I think another big question to answer with this approach is "What types of requests are we willing to handle?" Thinking about it I believe that Rack::Request, ActionDispatch::Request, and Net::HTTPRequest are good places to start. It does put the library in a weird place of rejecting requests based off of the class of request it is, but I'm not sure there is a better way if HMAC needs to be supported for API's being called from Millennium.

**Comment by nbeyer** [comment]
Closed with #11
